### ISSUE TITLE
Issue with removing clamp

### ISSUE THREAD

**Issue by drhannibalseca** [Virgildev/v-parking#1]
![3rdeye](https://github.com/user-attachments/assets/368ca1b1-738f-47a0-b31b-efde509b85fc)
Hello

When I look at the tire or car, I do not get an option to slash tires, Im running ox_lib, target and inventory.
Also when I go to the ped to ped a ticket and 3rd eye nothing shows up, but the ped that spawns the vehicle works

**Comment by Virgildev** [comment]
You must have a knife in hand and out before you can slash a tire. 

Fixed push to github for the not being able to target, for some reason I job locked the ticket payment menu.
